### ISSUE TITLE
Error during setup of component yamaha_soundbar

### ISSUE THREAD

**Issue by garagara93** [osk2/yamaha-soundbar#12]
Hi, the addon doesn't work. 
HA 2024.5.0

log 

Registratore: homeassistant.setup
Fonte: setup.py:404
Prima occorrenza: 00:18:09 (1 occorrenze)
Ultima registrazione: 00:18:09

Error during setup of component yamaha_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yamaha_soundbar/__init__.py", line 175, in setup
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'yamaha_soundbar' calls async_register from a thread at custom_components/yamaha_soundbar/__init__.py, line 175: hass.services.async_register(. Please report it to the author of the 'yamaha_soundbar' custom integration.

**Comment by catduckgnaf** [comment]
you must have been reading my mind! just submitted a fix for this.
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/compare/3.2.0...3.2.1

**Comment by garagara93** [comment]
> you must have been reading my mind! just submitted a fix for this. [nagyrobi/home-assistant-custom-components-linkplay@3.2.0...3.2.1](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/compare/3.2.0...3.2.1)

So, what I have to do?

**Comment by catduckgnaf** [comment]
> > you must have been reading my mind! just submitted a fix for this. [nagyrobi/home-assistant-custom-components-linkplay@3.2.0...3.2.1](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/compare/3.2.0...3.2.1)
> 
> So, what I have to do?

wait for @osk2 to merge my pr. then update via hacs

**Comment by osk2** [comment]
We have just released version 3.2.3, which resolves the issue.

**Comment by garagara93** [comment]
Thank you so much guys!! It works.
