### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by NiiiYaa** [osk2/yamaha-soundbar#14]
Hello,

The "Home assistant Yamaha soundbar" stopped working.

My device is: Yas209.

The entity status show now:
"This entity is no longer being provided by the yamaha_soundbar integration. If the entity is no longer in use, delete it in settings."

The log is:
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:364
integration: Media player (documentation, issues)
First occurred: July 7, 2024 at 10:53:57 AM (1 occurrences)
Last logged: July 7, 2024 at 10:53:57 AM

Error while setting up yamaha_soundbar platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/yamaha_soundbar/media_player.py", line 275, in async_setup_platform
    yamaha = YamahaDevice(name,
             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yamaha_soundbar/media_player.py", line 313, in __init__
    self._factory = UpnpFactory(requester, disable_unknown_out_argument_error=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UpnpFactory.__init__() got an unexpected keyword argument 'disable_unknown_out_argument_error'

My HA details are:
Core: 2024.7.1
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240705.0

And by the way - this integration is not available anymore via the HACS (I couldn't find it there anymore).

**Comment by dnikles** [comment]
This should get the integration to load again
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues/145#issuecomment-2207035710

**Comment by NiiiYaa** [comment]
@dnikles 
indeed, I applied this change (I corrected it manually with in the 'media_player.py' file) and that fixed it and now it is working again.
Thank you!
