### ISSUE TITLE
Homeassistant errors

### ISSUE THREAD

**Issue by noname-ever** [osk2/yamaha-soundbar#4]
This HACS integration generates many errors. This snippet includes 207 occurrences after a recent restart.

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/linkplay/media_player.py:2678
Integration: Linkplay (documentation, issues)
First occurred: 11:55:01 (207 occurrences)
Last logged: 12:33:32

Update for media_player.duokim_garo fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/config/custom_components/linkplay/media_player.py", line 818, in async_update
    await self.async_update_via_upnp()
  File "/config/custom_components/linkplay/media_player.py", line 2678, in async_update_via_upnp
    xml_tree = ET.fromstring(media_metadata)
  File "/usr/local/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 15, column 38

Maybe you could take a look?

**Comment by osk2** [comment]
What's your device model? I don't have this problem with my YAS-209.

**Comment by tomasz8w** [comment]
I also spotted errors like that with YAS-209 and yes, they're quite often

**Comment by noname-ever** [comment]
> What's your device model? I don't have this problem with my YAS-209.

I own "YAS-209". I can provide all the information you need in order to get to the root cause of the issue.

**Comment by osk2** [comment]
I was unable to reproduce these errors on my YAS-209 (firmware v5.31).

Things I tried:
1. Play sound in TV mode
2. Play sound in network mode (using Spotify)

None of these resulted in the error you experienced. Could you provide the steps that led to this error?

**Comment by noname-ever** [comment]
There is no specific action I have to take. That error simply appears out of nowhere. I will try to find under what circumstances it actually happens.
It seems to me that new HA version provides lesser amount of errors.

**Comment by idogrf** [comment]
I had the same issues just now
The message popped up multiple time per minute for a couple of hours!
Restarting home assistant didn't work
Restarting the sound bar itself (YAS-209) worked
