### ISSUE TITLE
yas-109 connection errors

### ISSUE THREAD

**Issue by LorenzoBianconi** [osk2/yamaha-soundbar#6]
hi @osk2 

thx for your work on supporting yamaha-soundbar device. 
I have the following warnings in HA logs that cause the connection reset to my yas-109:

WARNING (MainThread) [custom_components.linkplay.media_player] Failed async communicating with LinkPlayDevice (httpapi) 'YAS_109': <class 'TimeoutError'>
...

it occurs multiple times and I need to manually power the device up (e.g. to use Alexa commands). Any hint about the root cause of the problem?
The firmware running on the soundbar is 5.31.

Regards,
Lorenzo

**Comment by osk2** [comment]
Did you check your router? It seems like the connection is unstable.
