### ISSUE TITLE
Addon not working anymore

### ISSUE THREAD

**Issue by papka1974** [osk2/yamaha-soundbar#7]
HA 2023.10.5. Addon stopped working. Within log getting such warning "Setup of media_player platform linkplay is taking over 10 seconds.". No sound bar access anymore.

**Comment by osk2** [comment]
I'm not having any issues with 2023.11.2. Perhaps you could try rebooting your sound bar?

**Comment by papka1974** [comment]
Sorry. You're right. I was only restarted HA, not sound bar, since it work fine with original app. After restarting soundbar and then HA everything working. Please close  issue.
